
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Jun 01 15:03:47 CST 2013
//----------------------------------------------------

package decency.compiler;

/** CUP generated interface containing symbol constants. */
public interface Symbols {
  /* terminals */
  public static final int RBRACK = 13;
  public static final int LT = 7;
  public static final int SEMICOLON = 9;
  public static final int PLUS = 22;
  public static final int RBRACE = 17;
  public static final int RPAREN = 11;
  public static final int INT = 8;
  public static final int WHILE = 18;
  public static final int LBRACK = 12;
  public static final int RETURN = 4;
  public static final int LPAREN = 10;
  public static final int GT = 6;
  public static final int LBRACE = 16;
  public static final int ID = 25;
  public static final int NUM = 26;
  public static final int MULASS = 21;
  public static final int INC = 2;
  public static final int COMMA = 14;
  public static final int EOF = 0;
  public static final int ASTER = 24;
  public static final int DEC = 3;
  public static final int MINUS = 23;
  public static final int error = 1;
  public static final int SUBASS = 20;
  public static final int ASSIGN = 15;
  public static final int ADDASS = 19;
  public static final int FOR = 5;
}

